### ISSUE TITLE
Appending Drawable not possible

### ISSUE THREAD

**Issue by yayaa** [IanGClifton/AndroidFloatLabel#19]
I needed to add a drawable to this floatingLabel's right but the native method is not working, i tried to do it like:

myFloatLabel.getEditText().setCompoundDrawables(null, null, getResources().getDrawable(R.drawable.icon), null);

But this has no effect. Is there any way to achieve this?

**Comment by IanGClifton** [comment]
If you use setCompoundDrawables, you must already have the bounds defined on the drawables you pass.  If you just want the default intrinsic bounds, you should change your call to myFloatLabel.getEditText().setCompoundDrawablesWithIntrinsicBounds(0, 0, R.drawable.icon, 0);
