### ISSUE TITLE
Resource conflict: ic_launcher / app icon in library

### ISSUE THREAD

**Issue by clemp6r** [IanGClifton/AndroidFloatLabel#22]
After adding your lib to my app dependencies I cannot build my project:

```
Error:(13, 9) Execution failed for task ':app:processDevDebugManifest'.
Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher) from AndroidManifest.xml:13:9
	is also present at com.iangclifton.android:floatlabel:1.0.2:12:9 value=(@drawable/ic_launcher)
	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:10:5 to override
```

I'm not sure it is relevant to have a launcher icon in a library. Can you remove it?

**Comment by IanGClifton** [comment]
Should be fixed now in master and tag v1.0.3.  I've pushed the changes to Maven Central, so you should be able to use compile 'com.iangclifton.android:floatlabel:1.0.3' soon.  Let me know if that fixes your issue.
