### ISSUE TITLE
Remove unused resources

### ISSUE THREAD

**Issue by nschwermann** [IanGClifton/AndroidFloatLabel#25]
There is a few ic_launcher icons in the library I'm not sure what else.

**Comment by IanGClifton** [comment]
There aren't any drawables in the library portion (https://github.com/IanGClifton/AndroidFloatLabel/tree/master/FloatLabel/res), only in the example app.  Unless you're seeing something I'm not?

**Comment by nschwermann** [comment]
I'm getting ic_launcher icons coming through on gradle in drawable_<dpi>_v4 folders on version 1.0.2

**Comment by IanGClifton** [comment]
The current version is 1.0.4, but the drawables should also be gone in 1.0.3.

**Comment by nschwermann** [comment]
Oh great I will upgrade thanks!

On Wed, May 27, 2015 at 12:10 PM, Ian G. Clifton notifications@github.com
wrote:

> The current version is 1.0.4, but the drawables should also be gone in
> 1.0.3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IanGClifton/AndroidFloatLabel/issues/25#issuecomment-106000300
> .

## 

_Nathan Schwermann_
_785-312-0080_
_http://schwiz.net http://schwiz.net_
